#+TITLE:Hello,world
* 关于博客
** 我与博客
最早接触博客，是三年前吧，那时候上大一。

当时微博慢慢火了起来，我也是在接触微博的过程中，开始关注博客。但是新鲜劲过去之后，就什么都没有了
之后也看了几家比较小众的博客网站，虽然看似比大网站提供的博客个性许多，但终究还是提不起兴趣

关于传统的博客，我觉得有如下这几点，是我当时不喜欢用它的原因
+ 博客的模版太过死板。博客服务提供商提供的DIY服务有限，无法彰显个性
+ 博客不同于微博，博客需要大量的内容做填充。当时没有什么想要表达的东西，一句话，没有货
+ 写博客，不仅需要自己有内容，还要有时间，不仅要有时间，还要能静得下心来。时间，我有，但是心静不下来
现在呢，上述缺少的条件，博客的个性，内容，时间，心静，基本上算是有了吧。所以想要写博客的年头就又一次出现在脑海里，我的博客生涯应该是从此开始了吧
** 对博客内容的定位
技术与人文
*** 技术类
+ 语言的学习
+ 工具的使用
+ 具体开发的项目
*** 人文类
+ 非技术书籍的阅读
+ 个人经历与感悟
+ 趣事听闻

** 对博客版式的定位
让事情变得简单。
+ 简洁
+ 紧凑
+ 统一
+ 有逻辑
** 博客的读者
本博客主要用来自己记录自己的学习过程，感悟，以及方便与他人传递信息。不提供在线的评论功能。
* 关于搜索引擎
** 搜索引擎的选择
对于学习来说，互联网最大的好处就是搜索引擎的诞生。

各大搜索引擎各有特点。但是，要是选择其中一个作为自己的常用搜索引擎的话，应该选择google。google是世界上的当之无愧最好的搜索引擎，如果要是做技术方面的搜索，google更是无出其右。
** 对搜索内容的学习
google虽然已经非常厉害，但是依旧是机器人。搜索的文章还是要自己进行一定的筛选。筛选的时候，需要关注的几个点，主要是
+ 时间：文章都有一定的实效性。文章也不是越新越好，对症下药最好。因为自己的问题可能也是一个非常老的问题，那么看最新的文章也解决不了问题。
+ 作者：具有一定权威的作者的内容，当然还是首选。不过，也有很多作者，小众，但是内容非常好。
+ 比较：对于同一问题，在不确定搜索出来的解决方案是否是最优的时候，应该多看几篇同类型的文章，对关注的同一细节进行多方面的比较。
** 与搜索引擎交流
google的背后是机器与算法。机器与算法遵循一定的规律，并非真的只能。应该学会与其有效的交流。学习一些google的高级用法是必要的。
* 关于外语
英语是计算机世界里的官方交流语言。许多经典书籍，最新的技术进展都是用英文写成的。所以，学好英语至关重要。

学习方法
+ 阅读需要学习的相关书籍的英文文档和书籍，多记多倍关键单词和表达方式，留意英文的表达方式
+ 接触一些英文的音像制品。美剧，英文歌曲，电台节目
+ 与母语是英语的人进行直接的交流。比如上一些国外的irc频道
* 关于Hello，world
 Hello，world !，就像是programmer的身份证。这个传统应该是很多年前的前辈，用程序语言写出的第一个实现，或者给人看到的第一个实现。从此以后，
每当我们基础一门新技术，只要是可以实现Hello，world ！输出的，必然是第一选择。我也不能免俗，用很多语言，写了很多版本的Hello,world!。C,C++,Objective-C,shell,Ruby,Python,Emacs Lisp,C#......
所以，第一篇文章就用 Hello，world !来向前辈们致敬，也宣告自己博客的诞生吧。

Hello,world !

你好，世界！


